{
 "title": "API Bench",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API Instances",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"api\"}",
     "legendFormat": "Current {{ deployment }}"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=\"api\"}",
     "legendFormat": "Max {{ horizontalpodautoscaler }}"
    }
   ]
  },
  {
   "title": "Nginx Instances",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=~\"nginx-ingress-nginx-controller\"}",
     "legendFormat": "Current {{ deployment }}"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=\"nginx-ingress-nginx-controller\"}",
     "legendFormat": "Max {{ horizontalpodautoscaler }}"
    }
   ]
  },
  {
   "title": "API CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"api\"}[5m]))",
     "legendFormat": "Current {{ deployment }}"
    }
   ]
  },
  {
   "title": "HTTP Requests / s",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_requests{ingress=\"api\"}[1m])",
     "legendFormat": "[{{ status }}]"
    }
   ]
  },
  {
   "title": "HTTP Latency",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"api\"}[5m])) by (ingress,le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"api\"}[5m])) by (ingress,le))",
     "legendFormat": "99%"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_sum{ingress=\"api\"}[5m])) / sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"api\"}[5m]))",
     "legendFormat": "Mean"
    }
   ]
  }
 ]
}