grafana.ini:
  auth.anonymous:
    enabled: true
  server:
    domain: ${domain}

rbac:
  pspEnabled: false
testFramework:
  enabled: false

sidecar:
  dashboards:
    enabled: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prom-op-prometheus
        access: proxy
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/dashboards

resources: ${jsonencode(resources)}

nodeSelector:
  nodepool: ${label}

ingress:
  enabled: true
  annotations:
    "kubernetes.io/ingress.class": ${ingress_class}
    "nginx.ingress.kubernetes.io/auth-type": basic
    "nginx.ingress.kubernetes.io/auth-secret": ${basic_auth_secret}
  hosts:
    - ${domain}
